# Generated by Django 4.2.5 on 2023-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productbrand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول'),
        ),
    ]
